### ISSUE TITLE
IndexDocumentProducer should not generate id

### ISSUE THREAD

**Issue by hobofan** [mariamhakobyan/elasticsearch-river-kafka#15]
At the moment the IndexDocumentProducer genereates an id for every indexRequest via `.id(UUID.randomUUID().toString())`.

[From the ES docs:](http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/bulk.html)
>If no _id is specified, an ID will be autogenerated

Therefore, there is no reason to generate an id in this river.

One reason why the id should no be generated is because it prevents the `_id` from being set through a document field specified in `_id.path`

**Comment by jamespedwards42** [comment]
Didn't notice the existing PR... +1 vote for this change.

**Comment by mariamhakobyan** [comment]
Hi @hobofan & @jamespedwards42,

Thanks for your contribution. I added those changes to master. Will be available with the next release.

Cheers,
Mariam
