### ISSUE TITLE
Raw Execute Method

### ISSUE THREAD

**Issue by schonfeld** [mariamhakobyan/elasticsearch-river-kafka#9]
Hey! 

Could you please possibly outline how I should use the raw execute action type?

I'm especially curious if I can create an `update` type request using that action... Something with both a doc upsert, and an update script.

**Comment by mariamhakobyan** [comment]
Hi @schonfeld,

Sure, using raw execute action type you can do that. You can pass the string from Kafka, containing the commands you want, like index, delete, update requests. 

Here is one example, that one of the users passes as a message from Kafka:

```
String bulkRequest = "{ \"index\" : { \"_index\" : \"twitter\", \"_type\" : \"tweet\", \"_id\" : \"1\" } }\n" +
                    "{ \"tweet\" : { \"text\" : \"this is a tweet\" },\"user\" : {\"text\":\"testing\"} }\n" +
                    "{ \"delete\" : { \"_index\" : \"twitter\", \"_type\" : \"tweet\", \"_id\" : \"2\" } }\n" +
                    "{ \"create\" : { \"_index\" : \"twitter\", \"_type\" : \"tweet\", \"_id\" : \"1\" } }\n" +
                    "{ \"tweet\" : { \"text\" : \"another tweet\" } }";
producer.send( new KeyedMessage<String, String>(topic, bulkRequest ) );
```

Let me know if you still have open questions, and thanks for your interest in this river project.

Cheers,
Mariam

**Comment by schonfeld** [comment]
Thanks, @mariamhakobyan. That answers it. I'll go ahead and create a PR for a readme update that includes these instructions. Sounds good?

**Comment by mariamhakobyan** [comment]
@schonfeld, actually the Readme already includes the information about raw type, do you think it's not enough or you want to add the example which I brought up?

**Comment by schonfeld** [comment]
It's def not abundantly obvious on first read. Maybe just a link to [Elasticsearch's Bulk API docs](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-bulk.html) would suffice...

**Comment by mariamhakobyan** [comment]
Sure, feel free to add a link to that page, and an example as well if you have a corresponding one, and send a PR!
